"""
Configuration module for Cree Whisper ASR training.

This module centralizes all file paths, model parameters, and 
hardware configurations. It ensures a single source of truth 
for both the training and testing scripts.
"""

import os

# ==========================================
# 1. DATA AND HARDWARE CONFIGURATIONS
# ==========================================
# Number of CPU cores to allocate for dataset mapping.
# Adjusted to 24 to utilize a majority of the 32-core Ryzen desktop.
NUM_PROC: int = 24

# Seed for deterministic splitting of the dataset.
RANDOM_SEED: int = 42

# Proportion of the dataset to reserve for evaluation (10%).
TEST_SIZE: float = 0.1

# Sampling rate expected by Whisper.
SAMPLING_RATE: int = 16000

# ==========================================
# 2. PATH CONFIGURATIONS
# ==========================================
# Assuming the model is downloaded locally for offline SLURM usage.
# Change this to an absolute local path if the cache is unavailable.
BASE_MODEL_ID: str = "openai/whisper-tiny"

# Path to the dataset metadata generated by `wrap_sro_data.py`.
METADATA_CSV: str = "metadata.csv"

# Directories for saving outputs.
OUTPUT_DIR: str = "./whisper-tiny-cree-finetuned"
FINAL_MODEL_DIR: str = os.path.join(OUTPUT_DIR, "final")
TEST_RESULTS_TSV: str = "test_results.tsv"

# ==========================================
# 3. TRAINING HYPERPARAMETERS
# ==========================================
TRAIN_BATCH_SIZE: int = 4
GRAD_ACCUM_STEPS: int = 4
LEARNING_RATE: float = 1e-5
WARMUP_STEPS: int = 200
MAX_STEPS: int = 2000
SAVE_STEPS: int = 500
EVAL_STEPS: int = 500
LOGGING_STEPS: int = 50