[project]
name = "whisper-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "datasets[audio]>=4.8.4",
    "evaluate>=0.4.6",
    "gradio>=6.11.0",
    "jiwer>=4.0.0",
    "pipdeptree>=2.34.0",
    "tensorboard>=2.20.0",
    "transformers>=5.5.0",
]
