"""
Evaluation module for testing fine-tuned Whisper on Cree.

This script isolates the exact testing fold generated by the
training run using identical dataset splitting parameters.
It calculates Character Error Rate (CER) and Word Error Rate (WER).
"""

import csv
import torch
import evaluate

from datasets import load_dataset, Audio, DatasetDict
from transformers import pipeline

# Import our custom configuration to maintain synchronization
import config


def main() -> None:
    """
    Execute the inference evaluation pipeline.

    Loads the identical test set split, infers text via the pipeline,
    computes evaluation metrics, and saves raw transcripts to a TSV.

    Examples
    --------
    >>> if __name__ == "__main__":
    ...     main()
    """
    print("Loading Fine-Tuned Cree Whisper Model for Evaluation...")

    # Load dataset utilizing kwarg convention
    dataset_full = load_dataset(
        path="csv",
        data_files=config.METADATA_CSV,
        split="train"
    )

    dataset_full = dataset_full.cast_column(
        column="audio",
        feature=Audio(sampling_rate=config.SAMPLING_RATE)
    )

    # CRITICAL: Preserve random seed and test size exact configuration
    # so we test against the identical files withheld during training.
    dataset: DatasetDict = dataset_full.train_test_split(
        test_size=config.TEST_SIZE,
        seed=config.RANDOM_SEED
    )
    test_dataset = dataset["test"]

    device: str = "cuda:0" if torch.cuda.is_available() else "cpu"

    # Define strict pipeline loading
    transcriber = pipeline(
        task="automatic-speech-recognition",
        model=config.FINAL_MODEL_DIR,
        tokenizer=config.FINAL_MODEL_DIR,
        feature_extractor=config.FINAL_MODEL_DIR,
        device=device
    )

    wer_metric = evaluate.load(path="wer")
    cer_metric = evaluate.load(path="cer")

    references: list[str] = []
    predictions: list[str] = []
    results_data: list[list[str]] = []

    total_samples: int = len(test_dataset)
    print(f"Evaluating {total_samples} samples. This may take a moment.")

    # Iterate through the split test set for metric acquisition
    for i in range(total_samples):
        sample = test_dataset[i]
        audio_array = sample["audio"]["array"]
        ground_truth: str = sample["sentence"]
        audio_path: str = sample["audio"]["path"]

        # Execute transcript generation
        prediction: str = transcriber(audio_array)["text"]

        references.append(ground_truth)
        predictions.append(prediction)

        # Store layout mapping for file serialization
        results_data.append([audio_path, ground_truth, prediction])

    print(f"Writing detailed predictions to {config.TEST_RESULTS_TSV}...")
    with open(
        file=config.TEST_RESULTS_TSV,
        mode="w",
        encoding="utf-8",
        newline=""
    ) as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["audio_path", "reference_sro", "predicted_sro"])
        writer.writerows(results_data)

    wer: float = wer_metric.compute(
        predictions=predictions,
        references=references
    )
    cer: float = cer_metric.compute(
        predictions=predictions,
        references=references
    )

    # Emit human-readable performance characteristics
    print("\n" + "="*50)
    print("FINAL EVALUATION METRICS")
    print("="*50)
    print(f"Word Error Rate (WER):      {wer * 100:.2f}%")
    print(f"Character Error Rate (CER): {cer * 100:.2f}%")
    print("="*50 + "\n")


if __name__ == "__main__":
    main()
